spring:
  cloud:
    config:
      override-system-properties: false # Properties fetched from the config server should not override the ones at service fetching level

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka