server:
  port: 8086

spring:
  # Mongo - these configurations match the ones defined for Mongo Database in docker-compose file
  data:
    mongodb:
      username: nero
      password: nero
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin
