server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: mysql
    password: mysql
    driver-class-name: org.mysql.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config: # Ports of the API Gateway here
    customer-url: http://localhost:8555/api/v1/customers
    product-url: http://localhost:8555/api/v1/products
    payment-url: http://localhost:8555/api/v1/payments