server:
  port: 8083

spring:
  # Database configuration properties
  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # Kafka configuration properties
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # 'confirmation' represents the OrderConfirmation value passed to kafka order producer
        spring.json.type.mapping: orderConfirmation=com.workbeattalent.orderservice.kafka.OrderConfirmation


application:
  config: # Ports of the API Gateway here
    customer-url: http://localhost:8555/api/v1/customers
    product-url: http://localhost:8555/api/v1/products
    payment-url: http://localhost:8555/api/v1/payments