spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # 'paymentConfirmation' is the PaymentNotificationRequest object passed to the producer [SAME NAME]
        spring.json.type.mapping: paymentConfirmation=com.workbeattalent.paymentservice.payment.kafka.PaymentNotificationRequest

server:
  port: 8084